#!/bin/sh

# cleanup 

rm -rf obj_dir
rm -f top.vcd
rm -f counter.vcd
rm -f bin2bcd.vcd

# run Verilator to translate Verligo into C++, including C++ testbench 
verilator -Wall --cc --trace top.sv --exe top_tb.cpp
verilator -Wall --cc --trace counter.sv --exe top_tb.cpp
verilator -Wall --cc --trace bin2bcd.sv --exe top_tb.cpp

# build C++ project via make automatically generated by Verilator 
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation file 
obj_dir/Vtop